language: java
install:
    - wget https://cdn.getbukkit.org/spigot/spigot-1.16.1.jar && mvn install:install-file -Dfile=spigot-1.16.1.jar -DgroupId=org.spigotmc -DartifactId=spigot -Dversion=1.16.1-R0.1-SNAPSHOT -Dpackaging=jar
    - wget https://cdn.getbukkit.org/spigot/spigot-1.16.3.jar && mvn install:install-file -Dfile=spigot-1.16.3.jar -DgroupId=org.spigotmc -DartifactId=spigot -Dversion=1.16.3-R0.1-SNAPSHOT -Dpackaging=jar
    - wget https://cdn.getbukkit.org/spigot/spigot-1.16.5.jar && mvn install:install-file -Dfile=spigot-1.16.5.jar -DgroupId=org.spigotmc -DartifactId=spigot -Dversion=1.16.5-R0.1-SNAPSHOT -Dpackaging=jar
    - wget https://download.getbukkit.org/spigot/spigot-1.17.jar && mvn install:install-file -Dfile=spigot-1.17.jar -DgroupId=org.spigotmc -DartifactId=spigot -Dversion=1.17-R0.1-SNAPSHOT -Dpackaging=jar
    - wget https://download.getbukkit.org/spigot/spigot-1.17.1.jar && mvn install:install-file -Dfile=spigot-1.17.1.jar -DgroupId=org.spigotmc -DartifactId=spigot -Dversion=1.17.1-R0.1-SNAPSHOT -Dpackaging=jar
jdk: 
   - oraclejdk8
dist: trusty
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$TAGPERM@github.com/Paul19988/Advanced-Slime-World-Manager --tags
  - ls -R
deploy:
   provider: script
   script: .travis/release.sh
   skip_cleanup: true
   on:
    tags: true
